apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
    - name: hello
      image: busybox:v1
      command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      securityContext:
        allowPrivilegeEscalation: true
      livenessProbe:
        periodSeconds: 30
      readinessProbe:
        periodSeconds: 30
      resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 200m
              memory: 500Mi
