apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: test
spec:
  hostNetwork: false
  automountServiceAccountToken: false
  securityContext:
    runAsUser: 10
    seccompProfile:
            type: RuntimeDefault
  containers:
    - name: hello
      image: image@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c1234
      imagePullPolicy: Always
      command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      securityContext:
        runAsUser: 10000
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      livenessProbe:
        periodSeconds: 30
      readinessProbe:
        periodSeconds: 30 
      resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 200m
              memory: 500Mi
