apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  hosstNetwork: true
  securityContext:
    runAsUser: 10
  containers:
    - name: hello
      image: busybox:v1
      imagePullPolicy: Always
      command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["NET_RAW"]
      livenessProbe:
        periodSeconds: 30
      readinessProbe:
        periodSeconds: 30
      resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 200m
              memory: 500Mi
