apiVersion: v1
kind: RoleBinding
metadata:
  name: restricted-access
subjects:
- kind: user
  name: my-service-account
roleRef:
  kind: ClusterRole
  name: restricted-access
  apiGroup: rbac.authorization.k8s.io
