apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privilege-escalation
rules:
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterroles
  - roles
  verbs:
  - escalate
  - bind
