kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testrole
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create"]
