kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testrole
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["get","list","create"]
