apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privilege-escalation
rules:
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - ServiceAccount
  - Node
  verbs:
  - escalate
  - bind
---
apiVersion: v1
kind: RoleBinding
metadata:
  name: restricted-access
subjects:
- kind: ServiceAccount
  name: my-service-account
- kind: Node
  name: my-node
roleRef:
  kind: ClusterRole
  name: privilege-escalation
  apiGroup: rbac.authorization.k8s.io
