apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  securityContext:
    runAsUser: 10
  containers:
    - name: hello
      image: busybox
      command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      livenessProbe:
        periodSeconds: 3
