apiVersion: batch/v1
kind: CronJob
metadata:
  name: tom-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      securityContext:
              privileged: true
              hostPID: false
      template:
        spec:
          containers:
          - name: tom-container
            image: nginx:1.26 
          restartPolicy: OnFailure
