apiVersion: v1
kind: PodTemplate
metadata:
  name: jerry-pod-template
spec:
  metadata:
    labels:
      app: jerry-app
  spec:
    containers:
    - name: jerry-container
      image: nginx:latest
      securityContext:
        privileged: false
