apiVersion: batch/v1
kind: CronJob
metadata:
  name: jerry-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: jerry-container
            image: nginx:1.25.3  
            restartPolicy: OnFailure
