apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restrict-capabilities
spec:
  privileged: false  # Disallow privileged containers
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  volumes:
  - '*'
  allowedCapabilities: []  # Deny all capabilities
  hostNetwork: false
  hostIPC: false
  hostPID: false
  readOnlyRootFilesystem: false
