apiVersion: v1
kind: PodTemplate
metadata:
  name: jerry-podtemplate
spec:
  metadata:
    labels:
      app: jerry-app
  spec:
    containers:
    - name: your-container-name
      image: busybox:latest
      args: ["sleep", "3600"]
      ports:
      - containerPort: 80  
      securityContext:
        privileged: true  
      readinessProbe:
        httpGet:
          path: /
          port: 80  
        initialDelaySeconds: 5
        periodSeconds: 10
        failureThreshold: 3
