apiVersion: batch/v1
kind: Job
metadata:
  name: tom-job
spec:
  template:
    metadata:
      name: tom-pod
    spec:
      containers:
      - name: tom-container
        image: busybox:latest
        command: ["echo", "Hello, Job!"]
		securityContext:
          runAsNonRoot: true
      restartPolicy: Never
