apiVersion: batch/v1
kind: CronJob
metadata:
    name: kubernetes-cron-job
spec:
  schedule: "0/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cron-batch-job
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          containers:
          - name: tiller
            image: busybox:latest
            args: ["--listen=localhost:44134"]
          selector:
            app: helm
            name: tiller
          type: ClusterIP
