apiVersion: batch/v1
kind: Job
metadata:
  name: jobs-timeout-job
  namespace: test-kubequery-job
spec:
  selector:
    app: helm
    name: tiller
  template:
    spec:
      restartPolicy: Never
      containers:
        - command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
          image: perl
          name: jobs-timeout-container
