apiVersion: batch/v1
kind: Job
metadata:
  name: jerry-job
spec:
  template:
    metadata:
      labels:
        app: jerry-app
    spec:
      containers:
      - name: jerry-container
        image: busybox:latest
        ports:
        - containerPort: 80
          hostPort: 8080  
  backoffLimit: 3
