apiVersion: v1
kind: PodTemplate
metadata:
  name: pod-test
  namespace: test-kubequery-pod-templates
template:
  metadata:
    name: pod-template
  spec:
    automountServiceAccountToken: false
    containers:
      - name: my-container
        image: alpine
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        command:
        - kube-apiserver
        - --anonymous-auth=false
