apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: my-cronjob
        spec:
          securityContext:
            capabilities:
              drop:
                - ALL
          containers:
          - name: my-container
            image: nginx
            command:
            - "your-command"
  suspend: false
