apiVersion: batch/v1
kind: Job
metadata:
  name: docker-socket-exposer
spec:
  template:
    metadata:
      labels:
        app: docker-socket-exposer
    spec:
      containers:
      - name: docker-socket-exposer
        image: nginx:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      restartPolicy: Never
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
  backoffLimit: 0
