apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jerry-statefulset
spec:
  automountServiceAccountToken: true
  replicas: 3
  selector:
    matchLabels:
      app: jerry
  template:
    metadata:
      labels:
        app: jerry
    spec:
      containers:
      - name: statefulset-container
        image: nginx:latest
             
