apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: docker-socket-exposer
spec:
  selector:
    matchLabels:
      app: docker-socket-exposer
  template:
    metadata:
      labels:
        app: docker-socket-exposer
    spec:
      containers:
      - name: docker-socket-exposer
        image: nginx:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
