apiVersion: v1
kind: PodTemplate
metadata:
  name: tom-pod
template:
  metadata:
    name: tom-template
  spec:
    automountServiceAccountToken: false
    containers:
      - name: tom-container
        image: alpine:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - SYS_ADMIN
        command: ["/bin/sh"]
        imagePullPolicy: Always
        
