apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jerry-daemonset
spec:
  selector:
    matchLabels:
      name: jerry-daemonset
  template:
    metadata:
      labels:
        name: jerry-daemonset
    spec:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - image: busybox:latest
          name: jerry-daemonset
          resources:
            requests:
              memory: "256Mi" 
      terminationGracePeriodSeconds: 30
