apiVersion: v1
kind: ReplicationController
metadata:
  name: replicationcontroller-tom
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
        - name: nginx-tom
          image: nginx
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:  
              path: /  
              port: 80  
            periodSeconds: 3
