apiVersion: v1
kind: PodTemplate
metadata:
  labels:
    app: example-app
spec:
  metadata:
    labels:
      app: example-app
  spec:
    containers:
    - name: example-container
      image: nginx:latest
      securityContext:
        capabilities:
          drop:
          - ALL
          - NET_RAW
