apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jerry-replica
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx-containers
        image: nginx:latest
        securityContext:
          privileged: false
