apiVersion: batch/v1
kind: Job
metadata:
  name: tom-job
spec:
  template:
    metadata:
      labels:
        app: tom-job
    spec:
      containers:
      - name: tom-job-container
        image: nginx:latest
      restartPolicy: Never
