apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-in-env-fail-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jerry-app
  template:
    metadata:
      labels:
        app: jerry-app
    spec:
      containers:
      - name: tom-secret
        image: nginx:latest  
        env:
        - name: SECRET_ENV_VAR
          valueFrom:
            secretKeyRef:
              name: jerry-secret-name  
              key: jerry-secret-key
