apiVersion: v1
kind: PodTemplate
metadata:
  name: nginx-PodTemplate
spec:
  securityContext:
    runAsUser: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
