apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jerry-cronjob
spec:
  schedule: "*/1 * * * *" 
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: jerry-cronjobs
        spec:
          containers:
          - name: jerry-cronjobs
            image: nginx:latest
          restartPolicy: OnFailure
