apiVersion: apps/v1
kind: Deployment
metadata:
  name: jerry-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jerry-deployment
  template:
    metadata:
      labels:
        app: jerry-deployment
    spec:
      hostNetwork: true
      containers:
        - name: jerry-deployment-con
          image: nginx:latest
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
