apiVersion: batch/v1
kind: CronJob
metadata:
    name: kubernetes-cron-job
spec:
  schedule: "0/5 * * * *"
  jobTemplate:
    spec:
      selector:
    matchLabels:
      app: helm
      name: tiller
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helm
        name: tiller
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          containers:
          - name: tiller
            image: busybox:latest
            args:
            - --listen=localhost:44134
          
