apiVersion: v1
kind: ReplicationController
metadata:
  name: jerry-replicationcontroller
spec:
  automountServiceAccountToken: false
  replicas: 3
  selector:
    app: jerry
  template:
    metadata:
      labels:
        app: jerry
    spec:
      containers:
      - name: replicationcontroller-container
        image: busybox:latest
        command:
          - kube-controller-manager
          - --bind-address=127.10.11.1
