apiVersion: batch/v1
kind: Job
metadata:
  name: jobs-timeout-job
  namespace: test-kubequery-job
spec:
  activeDeadlineSeconds: 100
  template:
    metadata:
      labels:
        k8s-app: kubernetes-dashboard
    spec:
      restartPolicy: Never
      containers:
      - name: jobs-timeout-container
        image: busybox:latest
