apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: example-app
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000  # You can adjust this UID based on your requirements
          containers:
          - name: example-container
            image: nginx:latest
            command:
            - /bin/sh
            - -c
            - echo "Hello from the cron job!"
            securityContext:
              capabilities:
                add:
                - NET_ADMIN
          restartPolicy: OnFailure
