apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-cronjob
ports:
  - containerPort: 80
    hostPort: 8080
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-cronjob-container
            image: your-container-image:latest
          restartPolicy: OnFailure
