apiVersion: batch/v1
kind: Job
metadata:
  name: jerry-job
spec:
  template:
    metadata:
      labels:
        app: app-jerry-job
    spec:
      containers:
      - name: job-container
        image: busybox:latest
        command: ["echo", "Hello, World"]
        resources:
          requests:
            cpu: "0.1"
      restartPolicy: Never
  backoffLimit: 4
