apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: security-pass-daemonset
spec:
  selector:
    matchLabels:
      app: security-pass-daemonset
  template:
    metadata:
      labels:
        app: security-pass-daemonset
    spec:
      containers:
      - name: security-pass-container
        image: nginx:latest
        securityContext:
          capabilities:
            drop:
              - NET_RAW
      restartPolicy: Always
