apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tom-daemonset
spec:
  selector:
    matchLabels:
      app: tom-app
  template:
    metadata:
      labels:
        app: tom-app
    spec:
      containers:
      - name: tom-container
        image: busybox:latest
        ports:
        - containerPort: 80
          hostPort: 8080 
