apiVersion: v1
kind: PodTemplate
metadata:
  name: my-pod-template
spec:
  metadata:
    labels:
      app: my-app
  spec:
    automountServiceAccountToken: false
    containers:
    - name: my-container
      image: nginx:latest
      securityContext:
        Privilegd: true
