apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  hostPID: true
  securityContext:
    runAsUser: 10
  containers:
    - name: hello
      image: busybox:v1
      imagePullPolicy: Always
      command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
