apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: docker-socket-exposer
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: docker-socket-exposer
            image: nginx:latest
            securityContext:
              privileged: true
            volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
          restartPolicy: OnFailure
          volumes:
          - name: docker-socket
            hostPath:
              path: /var/run/docker.sock
