apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: disable-tiller-cronjob
spec:
  schedule: "0 0 * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: disable-tiller
            image: busybox:latest
            command:
            - /bin/sh
            - -c
            - kubectl scale deployment -n kube-system tiller-deploy --replicas=0
          restartPolicy: OnFailure
