apiVersion: v1
kind: PodTemplate
metadata:
  name: pod-test
  namespace: test-kubequery-pod-templates
template:
  metadata:
    name: pod-template
  spec:
    automountServiceAccountToken: false
    containers:
      - name: container
        image: alpine
        securityContext:
          allowPrivilegeEscalation: true
        command: ["/bin/sh"]
        args: ["-c", "sleep 100"]
        
