apiVersion: v1
kind: PodTemplate
metadata:
  name: tom-pod
template:
  metadata:
    name: tom-template
  spec:
    automountServiceAccountToken: false
    containers:
      - name: tom-container
        image: alpine
        securityContext:
          allowPrivilegeEscalation: false
        command: ["/bin/sh"]
        livenessProbe:
          httpGet:
            path: /healthz   
            port: 80         
          initialDelaySeconds: 15  
          periodSeconds: 10
