apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: jerry-container
spec:
  replicas: 3
  selector:
    app: jerry-app
  template:
    metadata:
      labels:
        app: jerry-app
    spec:
      containers:
      - name: jerry-container
        image: busybox:latest
        ports:
        - containerPort: 80
          hostPort: 8080  
