apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: security-daemonset
spec:
  selector:
    matchLabels:
      app: security-daemonset
  template:
    metadata:
      labels:
        app: security-daemonset
    spec:
      containers:
      - name: security-container
        image: busybox:latest
        securityContext:
          capabilities:
            drop:
              - NET_RAW
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-service-account
  namespace: default
