apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jerry-daemonset
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: jerry-app
    spec:
      containers:
      - name: daemon-container
        image: nginx:latest
      restartPolicy: Always
