apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example-cronjob
  namespace: your-namespace
spec:
  schedule: "*/5 * * * *"  # Adjust the schedule as needed
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: example
        spec:
          containers:
          - name: your-container
            image: your-image:tag
            command:
            - your-command
            - --anonymous-auth=false
            - --basic-auth-file=/path/to/basic-auth-file
          restartPolicy: OnFailure 
