apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubernetes-cron-jobs
spec:
  schedule: "0/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cron-batch-job
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          containers:
          - name: kube-cron-job
            image: busybox:latest
            command:
              - kube-apiserver
              - --enable-admission-plugins=AlwaysAdmit
              - --bind-address=192.168.1.1
