apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: your-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: your-app
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000  # Specify the desired non-root user ID
          containers:
          - name: your-container
            image: your-image:your-tag
            # Your container specifications go here
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
