apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tom-role-binding
  namespace: role-ns-binding
subjects:
- kind: ServiceAccount
  name: tom-service
roleRef:
  kind: Role
  name: tom-role
  apiGroup: rbac.authorization.k8s.io
