apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tom-daemonset
ports:
  - containerPort: 80
    hostPort: 8080
spec:
  selector:
    matchLabels:
      app: tom-app
  template:
    metadata:
      labels:
        app: tom-app
    spec:
      containers:
      - name: tom-container
        image: tom-container-image:latest
        ports:
        - containerPort: 80
