apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: seccomp-setup-cronjob
spec:
  schedule: "0 0 * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: seccomp-setup
            image: nginx:latest 
            command: ["/bin/sh", "-c"]
            args:
            - >
              docker info --format '{{.SecurityOptions}}' | grep -q 'seccomp:docker/default\|seccomp:runtime/default' &&
              echo "Seccomp profile is already set to docker/default or runtime/default." ||
              docker info --format '{{.ID}}' | xargs -I {} docker update --security-opt seccomp=docker/default {}
          restartPolicy: OnFailure
