apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: seccomp-profile-check
spec:
  schedule: "0 0 * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: seccomp-check
            image: nginx:latest
            command:
            - /bin/sh
            - -c
            - >
              if kubectl get pods -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.metadata.namespace}{"\t"}{.spec.securityContext.seccompProfile.type}{"\n"}{end}' | grep -q -E 'docker/default|runtime/default'; then
                echo "Seccomp profile is set to docker/default or runtime/default."
              else
                echo "Seccomp profile is not set to docker/default or runtime/default."
                exit 1  
              fi
          restartPolicy: OnFailure
