apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jerry-statefulset
spec:
  serviceName: "my-statefulset-service"
  replicas: 2
  selector:
    matchLabels:
      app: statefulset-testing
  template:
    metadata:
      labels:
        app: statefulset-testing
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        readinessProbe:
          httpGet:
            path: /
            port: 80 
          initialDelaySeconds: 5  
          periodSeconds: 10       
  volumeClaimTemplates:
  - metadata:
      name: data-statefulset
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
