apiVersion: batch/v1
kind: CronJob
metadata:
  name: tiller-cron-job
spec:
  schedule: "0/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: helm
            name: tiller
        spec:
          restartPolicy: OnFailure
          hostNetwork: true
          containers:
          - name: cron-job-jerry
            image: busybox:latest
            args: ["100"]
