apiVersion: batch/v1
kind: Job
metadata:
  name: tom-job
spec:
  template:
    metadata:
      labels:
        app: tom-app
    spec:
      containers:
      - name: tom-container
        image: nginx:latest
        command: ["echo", "Hello from the job!"]
  backoffLimit: 5
