apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: seccomp-setup-cronjob
spec:
  schedule: "1 0 * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: seccomp-setup
            image: your-docker-image:latest  
            command: ["/bin/sh", "-c"]
            args:
            - >
              if docker info --format '{{.SecurityOptions}}' | grep -q 'seccomp:docker/default\|seccomp:runtime/default'; then
                echo "Seccomp profile is already set to docker/default or runtime/default."
              else
                docker info --format '{{.ID}}' | xargs -I {} docker update --security-opt seccomp=docker/default {}
              fi
          restartPolicy: OnFailure
