apiVersion: v1
kind: ReplicationController
metadata:
  name: jerry-replicationcontroller
spec:
  replicas: 3
  selector:
    app: jerry
  template:
    metadata:
      labels:
        app: jerry
    spec:
      containers:
      - name: replicationcontroller-container
        image: busybox:latest
      restartPolicy: Always
