apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: your-desired-namespace
data:
  database_url: "jdbc:mysql://db.example.com:3306/mydb"
  api_key: "my-secret-api-key"
  log_level: "INFO"
