apiVersion: batch/v1
kind: CronJob
metadata:
    name: jerry-cron-job
spec:
  schedule: "0/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cron-batch-job
        spec:
          restartPolicy: OnFailure
          hostPID: true
          containers:
          - name: cron-job-jerry
            image: busybox:latest
            args: ["100"]
