apiVersion: batch/v1
kind: CronJob
metadata:
    name: tiller
    labels:
      app: tiller
spec:
  schedule: "0/5 * * * *"
  selector:
    matchLabels:
       app: helm
       name: tiller
    template:
        metadata:
          creationTimestamp: null
          labels:
            app: helm
            name: tiller
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          containers:
          - name: tiller
            image: image: gcr.io/kubernetes-helm/tiller:v2.16.9
            args:
            - --listen=localhost:44134
          
