apiVersion: batch/v1
kind: CronJob
metadata:
  name: tom-cronjob
spec:
  hostPID: flase
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tom-container
            image: nginx:1.26
          restartPolicy: OnFailure
