apiVersion: v1
kind: PodTemplate
metadata:
  name: pod-test
  namespace: test-kubequery-pod-templates
template:
  metadata:
    name: pod-template
  spec:
    automountServiceAccountToken: false
    containers:
      - name: container
        image: alpine:3
        securityContext:
          allowPrivilegeEscalation: false
        command: ["/bin/sh"]
        args: ["-c", "sleep 100"]
        resources:
          limits:
            memory: "256Mi"  
        volumeMounts:
          - name: varlog
            mountPath: /var/log
    volumes:
        - name: varlog
          hostPath:
              path: /var/log
