apiVersion: batch/v1
kind: CronJob
metadata:
  name: container-security-context-check
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: container-security-context-check
            image: ngionx:latest
          restartPolicy: OnFailure
