apiVersion: v1
kind: PodTemplate
metadata:
  name: tiller
  labels:
    app: helm
    name: tiller
template:
  metadata:
    name: tiller
  labels:
    app: helm
    name: tiller
  spec:
    automountServiceAccountToken: false
    restartPolicy: OnFailure
    containers:
    - name: tiller
      image: gcr.io/kubernetes-helm/tiller:v2.16.9
      args:
      - --listen
    selector:
        app: helm
        name: tiller
    type: ClusterIP
