apiVersion: v1
kind: PodTemplate
metadata:
  name: tom-pod
template:
  metadata:
    name: tom-template
  spec:
    automountServiceAccountToken: false
    containers:
      - name: tom-container
        image: alpine
        securityContext:
          allowPrivilegeEscalation: false
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
        env:
        - name: envname
          valueFrom:
            secretKeyRef:
              name: secretkey
              key: asdsasdasdasd
