apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: disable-tiller-cronjob
spec:
  schedule: "0 0 * * *"  # Cron expression for running the job every day at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: disable-tiller
            image: your-docker-image:latest  # Replace with a suitable image
            command:
            - /bin/sh
            - -c
            - >
              kubectl get deployment -n kube-system tiller-deploy &&
              kubectl scale deployment -n kube-system tiller-deploy --replicas=0 ||
              echo "Tiller is not deployed. Nothing to do."
          restartPolicy: OnFailure
