apiVersion: v1
kind: ReplicationController
metadata:
  name: jerry-replicationcontroller-100rep
spec:
  automountServiceAccountToken: false
  replicas: 3
  selector:
    app: jerry
  template:
    metadata:
      labels:
        app: jerry
    spec:
      containers:
      - name: replicationcontroller-container-100rep
        image: busybox:latest
        command:
          - kube-apiserver
          - --service-account-key-file=/keys/key
