apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: repltom-app
  template:
    metadata:
      labels:
        app: tom-app
    spec:
      containers:
      - name: tom-container
        image: nginx:latest
        securityContext:
              readOnlyRootFilesystem: true
        
