apiVersion: apps/v1
kind: Deployment
metadata:
  name: tom-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tom-app
  template:
    metadata:
      labels:
        app: tom-app
    spec:
      containers:
      - name: tom-container
        image: nginx:latest
        ports:
        - containerPort: 80
          hostPort: 8080  
