apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-job
spec:
  template:
    metadata:
      name: k8s-job
    spec:
      containers:
      - name: k8s-container
        image: nginx:latest
      restartPolicy: Never
