apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tom-statefulset
spec:
  serviceName: "tom"
  replicas: 3
  selector:
    matchLabels:
      app: tom-app
  template:
    metadata:
      labels:
        app: tom-app
    spec:
      containers:
      - name: tom-container
        image: nginx:latest
        ports:
        - containerPort: 80
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
          
