apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: your-cron-job
spec:
  schedule: "0 0 * * *"  # Cron expression for daily execution at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tom
            image: nginx:latest
            securityContext:
              allowPrivilegeEscalation: true
          restartPolicy: OnFailure
