apiVersion: v1
kind: PodTemplate
metadata:
  name: nginx-podtemplate
spec:
  metadata:
    labels:
      app: nginx
  spec:
    containers:
    - name: nginx-container
      image: nginx:latest
      ports:
      - containerPort: 80
