apiVersion: v1
kind: PodTemplate
metadata:
  name: your-podtemplate-name
spec:
  metadata:
    labels:
      app: your-app-label
  spec:
    containers:
    - name: your-container-name
      image: busybox:latest
      args: ["sleep", "3600"]
      ports:
      - containerPort: 80  # Update the port as needed
      securityContext:
        privileged: true  # Set to true to make the container privileged
      readinessProbe:
        httpGet:
          path: /
          port: 80  # Update the port as needed
        initialDelaySeconds: 5
        periodSeconds: 10
        failureThreshold: 3
