apiVersion: v1
kind: ReplicationController
metadata:
  name: security-scan-replicationcontroller
spec:
  replicas: 3  # Set the desired number of replicas
  selector:
    app: security-scan-replicationcontroller
  template:
    metadata:
      labels:
        app: security-scan-replicationcontroller
    spec:
      containers:
      - name: security-scan-container
        image: busybox:latest
        command:
          - "/bin/sh"
          - "-c"
          - >
            if capsh --print | grep -E 'ALL|all|NET_RAW'; then
              echo "Error: Container has prohibited capabilities" >&2
              exit 1
            else
              echo "Container passed security scan"
            fi
  restartPolicy: Always
