apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jerry-daemonset
spec:
  selector:
    matchLabels:
      app: jerry
  template:
    metadata:
      labels:
        app: jerry
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: daemon-container
        image: nginx:latest
      restartPolicy: Always
