apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tom-daemonset
spec:
  selector:
    matchLabels:
      app: testing-app
  template:
    metadata:
      labels:
        app: testing-app
    spec:
      containers:
      - name: busybox-container
        image: busybox:latest
        command: ["sleep", "3600"]
