apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: statefullset-app
  template:
    metadata:
      labels:
        app: statefulset-app
    spec:
      containers:
      - name: statefulset-container
        image: nginx:latest
        securityContext:
          privileged: false
