apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replication-controller
spec:
  replicas: 3  
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest  
        ports:
        - containerPort: 80
