apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jerry-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: replicaset-app
  template:
    metadata:
      labels:
        app: replicaset-app
    spec:
      containers:
      - name: replicaset-container
        image: nginx
	resources:
          requests:
            cpu: "0.1"
