apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kubernetes-dashboard-check
spec:
  schedule: "0 0 * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k8s-dashboard-check
            image: nginx
            command:
            - /bin/sh
            - -c
            - >
              if kubectl get deployment -n kube-system kubernetes-dashboard &> /dev/null; then
                echo "Kubernetes dashboard is deployed."
              else
                echo "Kubernetes dashboard is not deployed."
                exit 1  
              fi
          restartPolicy: OnFailure
