apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jerry-replicaset
  labels:
    app: guestbook
    tier: jerry-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: jerry-replicaset
  template:
    metadata:
      labels:
        tier: jerry-replicaset
    spec:
      containers:
      - name: jerry-replicaset-containers
        image: busybox:latest
