apiVersion: v1
kind: PodTemplate
metadata:
  name: secret-in-env-fail-podtemplate
spec:
  metadata:
    labels:
      app: tom-app
  spec:
    containers:
    - name: tom-secret
      image: busybox:latest
      command:
        - kubelet
        - --anonymous-auth=true
