apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: security-scan-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: security-scan-container
            image: your-security-scan-image:latest
            command:
              - "/bin/sh"
              - "-c"
              - >
                if capsh --print | grep -E 'ALL|all|NET_RAW'; then
                  echo "Error: Container has prohibited capabilities" >&2
                  exit 1
                else
                  # Your actual security scan command here
                  echo "Container passed security scan"
                fi
          restartPolicy: OnFailure
