apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "*/1 * * * *" # Run every minute
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: example-cronjob
        spec:
          containers:
          - name: example-cronjob
            image: your-container-image:tag
            # Add other container specifications as needed
            securityContext:
              readOnlyRootFilesystem: true
          restartPolicy: OnFailure
