apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: security-pass-deploymentconfig
spec:
  replicas: 3  
  selector:
    app: security-pass-deploymentconfig
  template:
    metadata:
      labels:
        app: security-pass-deploymentconfig
    spec:
      containers:
      - name: security-pass-container
        image: nginx:latest
        securityContext:
          capabilities:
            drop:
              - NET_RAW
