apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jerry-statefulset
spec:
  serviceName: "example"
  replicas: 3
  selector:
    matchLabels:
      app: jerry-app
  template:
    metadata:
      labels:
        app: jerry-app
    spec:
      containers:
      - name: jerry-container
        image: nginx:latest
        ports:
        - containerPort: 80
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
