apiVersion: v1
kind: ReplicationController
metadata:
  name: jerry-replication-controller
spec:
  replicas: 2
  selector:
    app: jerry-app
  template:
    metadata:
      labels:
        app: jerry-app
    spec:
      containers:
      - name: replication
        image: nginx:latest
        readinessProbe:
          httpGet:
            path: /
            port: 80 
          initialDelaySeconds: 5
          periodSeconds: 10     
