apiVersion: batch/v1
kind: Job
metadata:
  name: tom-job
spec:
  template:
    spec:
      containers:
      - name: tom-containers
        image: ubuntu:latest
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
