apiVersion: batch/v1
kind: Job
metadata:
  name: job-tom
spec:
  template:
    spec:
      containers:
      - name: job-containers
        image: busybox:latest
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        resources:
          limits:
            cpu: "0.5"
      restartPolicy: Never
  backoffLimit: 4
