apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: secret-in-env-fail-deploymentconfig
spec:
  replicas: 1
  selector:
    app: jerry-app
  template:
    metadata:
      labels:
        app: jerry-app
    spec:
      containers:
      - name: tom-secret
        image: busybox:latest
        command:
          - kube-apiserver
          - --service-account-lookup=true
