apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: jerry-deployement-config
spec:
  replicas: 3
  selector:
    app: jerry-deployement-config
  template:
    metadata:
      labels:
        app: jerry-deployement-config
    spec:
      containers:
        - name: jerry-dep-config-container
          image: busybox:latest
          ports:
            - containerPort: 80
