apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: security-pass-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: security-pass-container
            image: nginx:latest
            command:
              - "/bin/sh"
              - "-c"
              - >               
                echo "Container passed security check"
          restartPolicy: OnFailure
