apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tom-socket-security
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tom-socket-security
            image: nginx:latest
           
          restartPolicy: OnFailure
