apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            
            runAsUser: 1000
            runAsGroup: 1000
          containers:
          - name: job-container
            image: your-image:latest
          restartPolicy: OnFailure
