apiVersion: v1
kind: Pod
metadata:
  name: docker-socket-exposer
spec:
  containers:
  - name: docker-socket-exposer
    image: nginx:latest
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
