apiVersion: v1
kind: PodTemplate
metadata:
  name: tom-pod
  labels:
    app: kubernetes-dashboard
template:
  metadata:
    name: tom-template
    labels:
      app: kubernetes-dashboard
  spec:
    automountServiceAccountToken: false
    containers:
      - name: tom-container
        image: alpine@sha256:ba76950ac9eaa407512c9d859cea48114eeff8a6f12ebaa5d32ce79d4a017dd8
        securityContext:
          allowPrivilegeEscalation: false
