apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: jerry-deployment-config        
spec:
  replicas: 2
  selector:
    app: jerry-app-deployment-config
  template:
    metadata:
      labels:
        app: jerry-app-deployment-config
    spec:
      containers:
      - name: nginx-containers
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "0.1"
