apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tom-daemonset
spec:
  selector:
    matchLabels:
      app: demo-eg
  template:
    metadata:
      labels:
        app: demo-eg
    spec:
      containers:
      - name: busybox-container
        image: busybox:latest
	securityContext:
          runAsNonRoot: true
        command: ["sleep", "3600"]
