apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: jerry-deploymentconfig
spec:
  replicas: 1
  selector:
    app: deploymentconfig-app
  template:
    metadata:
      labels:
        app: deploymentconfig-app
    spec:
      containers:
      - name: deploymentconfig-container
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        securityContext:
          privileged: false
