apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jerry-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: tom-cronjob
        spec:
          containers:
          - name: tom-cronjob
            image: busybox:latest
            securityContext:
              runAsNonRoot: true
          restartPolicy: OnFailure
