apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: your-cron-job
spec:
  schedule: "0 0 * * *"  # Cron expression for daily execution at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: your-container
            image: your-image:latest  # Replace with your container image
            securityContext:
              allowPrivilegeEscalation: false
          restartPolicy: OnFailure
