apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: secret-in-env-fail-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app-label
  template:
    metadata:
      labels:
        app: your-app-label
    spec:
      containers:
      - name: container-with-secret
        image: your-docker-image:latest  
        env:
        - name: SECRET_ENV_VAR
          valueFrom:
            secretKeyRef:
              name: your-secret-name  
              key: your-secret-key    
      restartPolicy: Always
