apiVersion: v1
kind: PodTemplate
metadata:
  name: jerry-pod
template:
  metadata:
    name: jerry-template
  spec:
    automountServiceAccountToken: false
    containers:
      - name: jerry-container
        image: alpine
        securityContext:
          allowPrivilegeEscalation: false
        command: ["/bin/sh"]
        readinessProbe:   
          httpGet:       
            path: /
            port: 80         
          initialDelaySeconds: 5  
          periodSeconds: 10       
