apiVersion: v1
kind: PodTemplate
metadata:
  name: 113passpodtemplate
spec:
  metadata:
    labels:
      app: tom-app
  spec:
    containers:
    - name: tom-secret
      image: busybox:latest
      command:
        - kube-controller-manager
        - --bind-address=127.0.0.1
