apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tom-replicaset
  labels:
    app: guestbook
    tier: tom-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: tom-replicaset
  template:
    metadata:
      labels:
        tier: tom-replicaset
    spec:
      containers:
      - name: tom-replicaset-containers
        image: gcr.io/google_samples/gb-frontend:v3
		livenessProbe:
		  httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
