apiVersion: v1
kind: ReplicationController
metadata:
  name: jerry-replication-controller
spec:
  replicas: 3
  selector:
    app: jerry-app
  template:
    metadata:
      labels:
        app: jerry-app
    spec:
      containers:
      - name: jerry-container
        image: nginx:latest
        ports:
        - containerPort: 80
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
