apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
            fsGroup: 2000
          containers:
          - name: job-container
            image: nginx:latest
          restartPolicy: OnFailure
