apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: your-container
        image: your-docker-image:latest  # Replace with the appropriate image
        command: ["/bin/sh", "-c"]
        args:
        - >
          if [ "$(your-condition-check-command)" = "condition_met" ]; then
            echo "Condition is met. Setting seccomp profile."
            docker update --security-opt seccomp=docker/default $(docker ps -q)
          else
            echo "Condition is not met. Skipping seccomp setup."
          fi
      restartPolicy: Always
