apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: tiller-deploy
  namespace: kube-system
spec:
  replicas: 0
  selector:
    app: helm
    name: tiller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: helm
        name: tiller
    spec:
      containers:
      - name: tiller
        image: gcr.io/kubernetes-helm/tiller:v2.16.1  
