apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx
    spec:
      hostPID: false
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
