apiVersion: v1
kind: PodTemplate
metadata:
  labels:
    app: example-app
spec:
  securityContext:
    capabilities:
      add:
        - NET_ADMIN
  containers:
  - name: example-container
    image: nginx:latest
    ports:
    - containerPort: 80
  restartPolicy: Always
