apiVersion: batch/v1
kind: Job
metadata:
  name: jobs-timeout-job
  namespace: test-kubequery-job
spec:
  activeDeadlineSeconds: 100
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: jobs-timeout-container
        image: busybox:latest
        command:
          - kube-apiserver
          - --anonymous-auth=false
          - --basic-auth-file
          - --kubelet-https=false
