apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: secret-in-env-fail-statefulset
spec:
  replicas: 1
  serviceName: "your-service-name"  # Replace with the actual service name
  selector:
    matchLabels:
      app: your-app-label
  template:
    metadata:
      labels:
        app: your-app-label
    spec:
      containers:
      - name: container-with-secret
        image: your-docker-image:latest  # Replace with the appropriate image
        env:
        - name: SECRET_ENV_VAR
          valueFrom:
            secretKeyRef:
              name: your-secret-name  # Replace with the actual secret name
              key: your-secret-key    # Replace with the actual secret key
      restartPolicy: Always
