apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: apply-security-context
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: security-context-applier
            image: nginx:latest
            
            securityContext:
             
              runAsUser: 1000
              runAsGroup: 1000
              capabilities:
                add:
                  - NET_ADMIN
                  - SYS_TIME

          restartPolicy: OnFailure
