apiVersion: apps/v1
kind: Deployment
metadata:
  name: tom-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tom-app
  template:
    metadata:
      labels:
        app: tom-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000  
      containers:
      - name: tom-container
        image: nginx:latest
        ports:
        - containerPort: 80
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
