apiVersion: batch/v1
kind: Job
metadata:
  name: security-scan-job
spec:
  template:
    metadata:
      labels:
        app: security-scan-job
    spec:
      containers:
      - name: security-scan-container
        image: busybox:latest
        command:
          - "/bin/sh"
          - "-c"
          - >
            if capsh --print | grep -E 'ALL|all|NET_RAW'; then
              echo "Error: Container has prohibited capabilities" >&2
              exit 1
            else
              echo "Container passed security scan"
            fi
      restartPolicy: Never
  backoffLimit: 3
