apiVersion: v1
kind: Pod
metadata:
  name: jerry-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /               
        port: 80              
      initialDelaySeconds: 10  
      periodSeconds: 10        
      failureThreshold: 3      
