apiVersion: batch/v1
kind: Job
metadata:
  name: disable-tiller-job
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: disable-tiller
        image: busybox:latest
      selector:
        matchLabels:
          app: helm
          name: tiller
        command:
        - /bin/sh
        - -c
        - >
          if kubectl get deployment -n kube-system tiller-deploy &> /dev/null; then
            kubectl scale deployment -n kube-system tiller-deploy --replicas=0
          else
            echo "Tiller is not deployed. Nothing to do."
          fi
      restartPolicy: OnFailure
