apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: example
        spec:
          securityContext:
            
            runAsUser: 1000
            fsGroup: 2000
          containers:
          - name: job-container
            image: nginx:latest
            securityContext:
              
              runAsUser: 1000
              allowPrivilegeEscalation: false
          restartPolicy: OnFailure
