apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: jerry-deploymentconfig
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: busybox-container
          image: busybox:1.14.2
          ports:
            - containerPort: 80
