apiVersion: v1
kind: PodTemplate
metadata:
  name: tiller
  labels:
    app: helm
    name: tiller
template:
  metadata:
    name: tiller
  labels:
    app: helm
    name: tiller
  spec:
    automountServiceAccountToken: false
    containers:
      - name: tom-tiller
        port: 44134
        protocol: TCP
        targetPort: tiller
        image: alpine@sha256:ba76950ac9eaa407512c9d859cea48114eeff8a6f12ebaa5d32ce79d4a017dd8
    selector:
      app: helm
      name: tiller
    type: ClusterIP
