apiVersion: batch/v1
kind: Job
metadata:
  name: security-pass-job
spec:
  template:
    metadata:
      labels:
        app: security-pass-job
    spec:
      containers:
      - name: security-pass-container
        image: nginx:latest
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            add: ["NET_RAW"]
