apiVersion: v1
kind: PodTemplate
metadata:
  name: tom-pod
template:
  metadata:
    name: tom-template
  spec:
    automountServiceAccountToken: false
    containers:
      - name: tom-container
        image: alpine
        securityContext:
          allowPrivilegeEscalation: false
        command: ["/bin/sh"]
        resources:
          limits:
            cpu: 1
