apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jerry-statefulset-name
spec:
  serviceName: "jerry-statefulset-service"
  replicas: 3
  selector:
    matchLabels:
      app: jerry-app-label
  template:
    metadata:
      labels:
        app: jerry-app-label
    spec:
      containers:
      - name: jerry-container-name
        image: nginx:latest
  volumeClaimTemplates:
  - metadata:
      name: jerry-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "jerry-storage-class"
      resources:
        requests:
          storage: 1Gi
