apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tome-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tome-app
  template:
    metadata:
      labels:
        app: tome-app
    spec:
      containers:
      - name: tome-container
        image: nginx:latest
        ports:
        - containerPort: 80
