apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scan-container-conf
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scan-container-conf
            image: your/scanner-image:latest
            # Add other container specifications as needed
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
            env:
            - name: KUBE_CONFIG
              value: /kube/config
            volumeMounts:
            - name: kube-config
              mountPath: /kube/config
          volumes:
          - name: kube-config
            secret:
              secretName: your-kube-config-secret
          restartPolicy: OnFailure
