apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tom-daemonset
spec:
  selector:
    matchLabels:
      name: tom-daemonset
  template:
    metadata:
      labels:
        name: tom-daemonset
    spec:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
          name: tom-daemonset
      terminationGracePeriodSeconds: 30
