apiVersion: v1
kind: PodTemplate
metadata:
  labels:
    app: security-scan-podtemplate
spec:
  containers:
  - name: security-scan-container
    image: busybox:latest
    command:
      - "/bin/sh"
      - "-c"
      - >
        if capsh --print | grep -E 'ALL|all|NET_RAW'; then
          echo "Error: Container has prohibited capabilities" >&2
          exit 1
        else
          echo "Container passed security scan"
        fi
  restartPolicy: Always
