apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: busybox:latest
        command: ["echo", "Hello, Kubernetes!"]
        imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
