apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tom-cronjob
spec:
  schedule: "*/1 * * * *"  
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: example
        spec:
          containers:
          - name: jerry-container
            image: busybox:latest
            args:
            - /bin/sh
            - -c
            - ls
          restartPolicy: OnFailure






