apiVersion: apps/v1
kind: Deployment
metadata:
  name: tom-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tom-app
  template:
    metadata:
      labels:
        app: tom-app
    spec:
      automountServiceAccountToken: false
      containers:
        - name: tom-container
          image: alpine:latest
          securityContext:
            allowPrivilegeEscalation: false
          command: ["/bin/sh"]
          imagePullPolicy: IfNotPresent
