apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: example
        spec:
          containers:
          - name: cron-job-container
            image: busybox:latest
          - command:
            - kube-apiserver
            - --anonymous-auth=false
            - --basic-auth-file  
          restartPolicy: OnFailure
