apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tom-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tom-cronjob-container
            image: busybox:latest
