apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: disable-tiller-replicaset
  namespace: kube-system
spec:
  replicas: 0
  selector:
    matchLabels:
      app: helm
      name: tiller
  template:
    metadata:
      labels:
        app: helm
        name: tiller
    spec:
      containers:
      - name: dummy-container
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - sleep 365d
