apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: example-deploymentconfig
spec:
  replicas: 3
  selector:
    app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-container
        image: nginx:latest
        ports:
        - containerPort: 80
  strategy:
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
    type: Rolling
