apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jerry-statefulset
spec:
  serviceName: "jerry-service"
  replicas: 3
  selector:
    matchLabels:
      app: jerry-app
  template:
    metadata:
      labels:
        app: jerry-app
    spec:
      containers:
      - name: jerry-container
        image: nginx:latest
        ports:
        - containerPort: 80
          hostPort: 8080
