apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: secret-in-env-fail-daemonset
spec:
  selector:
    matchLabels:
      app: jerry-app
  template:
    metadata:
      labels:
        app: jerry-app
    spec:
      automountServiceAccountToken: false
      containers:
      - name: tom-con
        image: busybox:latest
        command:
        - kube-apiserver
        - --terminated-pod-gc-threshold=0
