apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: your-cronjob
spec:
  schedule: "*/5 * * * *"  # Cron expression for every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: your-container
            image: your-container-image:tag
            # Add other container specifications as needed
          restartPolicy: OnFailure  # or "Never" if you want the job to run only once
