apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jerry-daemonset
spec:
  selector:
    matchLabels:
      app: jerry
  template:
    metadata:
      labels:
        app: jerry
    spec:
      containers:
      - name: jerry-container
        image: busybox:latest
        
