apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: secret-in-env-fail-statefulset
spec:
  replicas: 1
  serviceName: "tom-service" 
  selector:
    matchLabels:
      app: your-app-label
  template:
    metadata:
      labels:
        app: your-app-label
    spec:
      containers:
      - name: tom-secret
        image: nginx:latest  
        env:
        - name: SECRET_ENV_VAR
          valueFrom:
            secretKeyRef:
              name: tom-secret-name  
              key: tom-secret-key   
      restartPolicy: Always
