apiVersion: batch/v1
kind: CronJob
metadata:
  name: jerry-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: jerry-container
            image: nginx:latest
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
          restartPolicy: OnFailure
