apiVersion: v1
kind: PodTemplate
metadata:
  labels:
    app: tom-app
spec:
  containers:
  - name: tom-container
    image: nginx:latest
    ports:
    - containerPort: 80
    securityContext:
      capabilities:
       add:
       - NET_ADMIN
  restartPolicy: Always
