apiVersion: v1
kind: ReplicationController
metadata:
  name: disable-tiller-replicationcontroller
  namespace: kube-system
spec:
  replicas: 0
  selector:
    app: helm
    name: tiller
  template:
    metadata:
      labels:
        app: helm
        name: tiller
    spec:
      containers:
      - name: dummy-container
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - sleep 365d
