apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-pass-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: security-pass-deployment
  template:
    metadata:
      labels:
        app: security-pass-deployment
    spec:
      containers:
      - name: security-pass-container
        image: nginx:latest
        securityContext:
          capabilities:
            drop:
              - NET_RAW
