apiVersion: v1
kind: Pod
metadata:
  name: pod-busybox
spec:
  containers:
    - name: container-busybox
      image: busybox
      command: ['sh', '-c', 'echo ""Hello, Kubernetes!"" && sleep 3600']
      securityContext:
        privileged: true"
