apiVersion: v1
kind: Pod
metadata:
  name: pod-busybox1-test1
spec:
  hostIPC: true
  hostNetwork: true
  containers:
    - name: container-busybox1
      image: busybox:latest
      command: ['sh', '-c', 'echo ""Hello, Kubernetes!"" && sleep 3600']
      securityContext:
        privileged: true
