apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: test
spec:
  hostNetwork: false
  automountServiceAccountToken: false
  securityContext:
    runAsUser: 10
    seccompProfile:
            type: RuntimeDefault
  containers:
    - name: hello
      image: image@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c1234
      imagePullPolicy: Always
      command:
      - kube-apiserver
      - --anonymous-auth=true
