apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: test
spec:
  hostNetwork: false
  automountServiceAccountToken: false
  securityContext:
    runAsUser: 10
    seccompProfile:
            type: RuntimeDefault
  containers:
    - name: hello
      image: busybox:v1
      imagePullPolicy: Always
      command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      securityContext:
        runAsUser: 10000
