apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: test
  labels:
    app: kubernetes-dashboard
spec:
  hostNetwork: false
  containers:
    - name: hello
      image: busybox:v1
      imagePullPolicy: Always
      command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
