apiVersion: v1
kind: Service
metadata:
  labels:
    app: helm
    name: tillerz
  name: tiller-deployz
  namespace: kube-system
spec:
  ports:
  - name: tillerz
    port: 44134
    protocol: TCP
    targetPort: tillerz
  selector:
    app: helm
    name: tillerz
  type: ClusterIP
