apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example-name
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "deployments", "configmaps", "services", "endpoints"]
    verbs: ["get", "watch", "list"]
